'use client';

import { useEffect, useState } from 'react';
import { ArrowUpRight, Search, Sparkles } from 'lucide-react';
import { Sidebar } from '@/components/layout/sidebar';
import { Header } from '@/components/layout/header';
import { TaskList } from './task-list';
import { SummaryCards, Deadlines, HabitsCard, WeeklyProgress } from './overview-cards';
import { InboxView } from '@/components/inbox/inbox-view';
import { TaskDialog } from './task-dialog';
import { SecondaryView } from './secondary-view';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { initialTasks, initialHabits } from '@/data/mock-data';
import type { MatrixQuadrant, Task, View } from '@/types/task';
import { cn } from '@/lib/utils';

export function Dashboard({ user }: { user: { name: string; email: string } }) {
  const [tasks, setTasks] = useState(() => initialTasks.map(task => ({ ...task, matrixQuadrant: task.matrixQuadrant ?? null }))); const [habits, setHabits] = useState(initialHabits); const [view, setView] = useState<View>('Inbox');
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [announcement, setAnnouncement] = useState(''); const [inboxComposing, setInboxComposing] = useState(false);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key === 'k') { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  const openAdd = () => { if (view === 'Inbox') { setInboxComposing(true); setMobileOpen(false); } else setAddOpen(true); };
  const toggle = (id: string) => setTasks(previous => previous.map(task => task.id === id ? { ...task, completed: !task.completed } : task));
  const toggleHabit = (id: string) => setHabits(previous => previous.map(habit => habit.id === id ? { ...habit, done: !habit.done } : habit));
  const today = tasks.filter(task => task.due === 'today'); const completed = today.filter(task => task.completed).length;
  const add = (task: Task) => { setTasks(previous => [{ ...task, matrixQuadrant: task.matrixQuadrant ?? null }, ...previous]); setAnnouncement(`Added: ${task.title}`); };
  const assignMatrixQuadrant = (id: string, matrixQuadrant: MatrixQuadrant | null) => { setTasks(previous => previous.map(task => task.id === id ? { ...task, matrixQuadrant } : task)); setAnnouncement(matrixQuadrant ? 'Task moved to the matrix.' : 'Task returned to Today’s tasks.'); };
  const secondary = <><div className="view-heading"><span className="section-kicker">YOUR PERSONAL WORKSPACE</span><h2>{view}</h2></div><SecondaryView view={view} tasks={tasks} toggle={toggle} add={openAdd} habits={habits} toggleHabit={toggleHabit} navigate={setView} assignMatrixQuadrant={assignMatrixQuadrant} /></>;
  const todayView = <><SummaryCards completed={completed} total={today.length} habitCount={habits.filter(habit => habit.done).length} priorities={today.filter(task => !task.completed && task.priority === 'high').length} /><div className="section-title"><div><span className="section-kicker">YOUR DAY, AT A GLANCE</span><h2>A little structure. More headspace.</h2></div><span className="today-pill"><span />Today</span></div><div className="dashboard-grid"><div className="main-column"><TaskList tasks={today} toggle={toggle} add={openAdd} /><WeeklyProgress navigate={setView} completed={completed} /></div><div className="aside-column"><Deadlines tasks={tasks} navigate={setView} /><HabitsCard habits={habits} toggle={toggleHabit} navigate={setView} /><button className="focus-note" onClick={() => setView('Eisenhower Matrix')}><Sparkles size={20} /><span><strong>Busy isn’t always productive.</strong><small>Find your focus with the Eisenhower Matrix.</small></span><ArrowUpRight size={18} /></button></div></div></>;
  return <div className={cn('app-shell', collapsed && 'sidebar-is-collapsed')}><a className="skip-link" href="#main">Skip to content</a><Sidebar view={view} setView={setView} collapsed={collapsed} toggle={() => setCollapsed(!collapsed)} search={() => setSearchOpen(true)} add={openAdd} count={today.length - completed} mobileOpen={mobileOpen} closeMobile={() => setMobileOpen(false)} userName={user.name} userEmail={user.email} /><main id="main" className="main-content">{view === 'Inbox' ? <InboxView tasks={tasks} composing={inboxComposing} setComposing={setInboxComposing} add={add} toggle={toggle} openMenu={() => setMobileOpen(true)} search={() => setSearchOpen(true)} /> : <><Header search={() => setSearchOpen(true)} add={openAdd} menu={() => setMobileOpen(true)} userName={user.name} userEmail={user.email} /><div className="workspace-content">{view === 'Today' ? todayView : secondary}<footer className="page-footer"><span>Made for progress, not perfection.</span><span>One day at a time <span className="footer-flower">✳</span></span></footer></div></>}</main><TaskDialog open={addOpen} onOpenChange={setAddOpen} add={add} /><Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="craft-dialog search-dialog"><DialogHeader><DialogTitle>Find your next thing</DialogTitle><DialogDescription>Search tasks across your workspace.</DialogDescription></DialogHeader><div className="search-input-wrap"><Search size={18} /><Input placeholder="Search tasks…" value={query} onChange={event => setQuery(event.target.value)} aria-label="Search tasks" /></div><div className="search-results">{tasks.filter(task => task.title.toLowerCase().includes(query.toLowerCase())).map(task => <button key={task.id} onClick={() => { setView(task.project === 'Inbox' ? 'Inbox' : task.due === 'today' ? 'Today' : task.due === 'inbox' ? 'Inbox' : 'Upcoming'); setSearchOpen(false); }}><span>{task.title}</span><small>{task.project} · {task.completed ? 'Completed' : task.due}</small></button>)}{!tasks.some(task => task.title.toLowerCase().includes(query.toLowerCase())) && <p>No tasks found. Try a different search.</p>}</div></DialogContent></Dialog><span role="status" className="sr-only">{announcement}</span></div>;
}
