'use client';

import { useCallback, useEffect, useState } from 'react';
import { ArrowUpRight, Search, Sparkles } from 'lucide-react';
import { Sidebar } from '@/components/layout/sidebar';
import { Header } from '@/components/layout/header';
import { TaskList } from './task-list';
import { SummaryCards, Deadlines, HabitsCard, WeeklyProgress } from './overview-cards';
import { InboxView } from '@/components/inbox/inbox-view';
import { TaskDialog } from './task-dialog';
import { SecondaryView } from './secondary-view';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { createWorkspaceTask, deleteWorkspaceTask, loadWorkspace, reorderWorkspaceTasks, toggleWorkspaceHabit, updateWorkspaceTask } from '@/features/workspace/workspace-client';
import { dateKey } from '@/lib/dates';
import type { Habit, MatrixQuadrant, Project, Task, TaskCreateInput, View } from '@/types/task';
import { cn } from '@/lib/utils';

export function Dashboard({ user }: { user: { name: string; email: string } }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [habits, setHabits] = useState<Habit[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [view, setView] = useState<View>('Inbox');
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [announcement, setAnnouncement] = useState(''); const [inboxComposing, setInboxComposing] = useState(false); const [loading, setLoading] = useState(true); const [workspaceError, setWorkspaceError] = useState('');
  const refreshWorkspace = useCallback(async () => { try { const workspace = await loadWorkspace(); setTasks(workspace.tasks); setHabits(workspace.habits); setProjects(workspace.projects); setWorkspaceError(''); } catch (cause) { setWorkspaceError(cause instanceof Error ? cause.message : 'Your workspace could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void refreshWorkspace(); }, 0); return () => window.clearTimeout(timer); }, [refreshWorkspace]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key === 'k') { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  const openAdd = () => { if (view === 'Inbox') { setInboxComposing(true); setMobileOpen(false); } else setAddOpen(true); };
  const add = async (task: TaskCreateInput) => { const saved = await createWorkspaceTask(task, projects); setTasks(previous => [saved, ...previous]); setAnnouncement(`Added: ${saved.title}`); };
  const toggle = async (id: string) => { const task = tasks.find(item => item.id === id); if (!task) return; try { const saved = await updateWorkspaceTask(id, { isCompleted: !task.completed }, projects); setTasks(previous => previous.map(item => item.id === id ? saved : item)); setAnnouncement(saved.completed ? `Completed: ${saved.title}` : `Reopened: ${saved.title}`); } catch (cause) { setWorkspaceError(cause instanceof Error ? cause.message : 'The task could not be updated.'); } };
  const updateTitle = async (id: string, name: string) => { const saved = await updateWorkspaceTask(id, { name }, projects); setTasks(previous => previous.map(task => task.id === id ? saved : task)); setAnnouncement(`Updated: ${saved.title}`); };
  const removeTask = async (id: string) => { await deleteWorkspaceTask(id); setTasks(previous => previous.filter(task => task.id !== id)); setAnnouncement('Task deleted.'); };
  const reorderTasks = async (ids: string[]) => { await reorderWorkspaceTasks(ids); const order = new Map(ids.map((id, index) => [id, index])); setTasks(previous => previous.map(task => order.has(task.id) ? { ...task, sortOrder: order.get(task.id)! } : task)); setAnnouncement('Task order saved.'); };
  const toggleHabit = async (id: string) => { const habit = habits.find(item => item.id === id); if (!habit || (!habit.done && !habit.isScheduledToday)) return; try { await toggleWorkspaceHabit(habit); await refreshWorkspace(); setAnnouncement(habit.done ? `Unchecked: ${habit.name}` : `Checked in: ${habit.name}`); } catch (cause) { setWorkspaceError(cause instanceof Error ? cause.message : 'The habit could not be updated.'); } };
  const assignMatrixQuadrant = async (id: string, matrixQuadrant: MatrixQuadrant | null) => { try { const saved = await updateWorkspaceTask(id, { matrixQuadrant }, projects); setTasks(previous => previous.map(task => task.id === id ? saved : task)); setAnnouncement(matrixQuadrant ? 'Task moved to the matrix.' : 'Task returned to Today’s tasks.'); } catch (cause) { setWorkspaceError(cause instanceof Error ? cause.message : 'The task could not be updated.'); } };
  const todayKey = dateKey(new Date()); const today = tasks.filter(task => task.scheduledDate === todayKey); const completed = today.filter(task => task.completed).length;
  const secondary = <><div className="view-heading"><span className="section-kicker">YOUR PERSONAL WORKSPACE</span><h2>{view}</h2></div><SecondaryView view={view} tasks={tasks} toggle={toggle} add={openAdd} habits={habits} toggleHabit={toggleHabit} navigate={setView} assignMatrixQuadrant={assignMatrixQuadrant} /></>;
  const todayView = <><SummaryCards completed={completed} total={today.length} habitCount={habits.filter(habit => habit.done).length} habitTotal={habits.length} priorities={today.filter(task => !task.completed && task.priority === 'high').length} /><div className="section-title"><div><span className="section-kicker">YOUR DAY, AT A GLANCE</span><h2>A little structure. More headspace.</h2></div><span className="today-pill"><span />Today</span></div><div className="dashboard-grid"><div className="main-column"><TaskList tasks={today} toggle={toggle} add={openAdd} /><WeeklyProgress navigate={setView} tasks={tasks} /></div><div className="aside-column"><Deadlines tasks={tasks} navigate={setView} /><HabitsCard habits={habits} toggle={toggleHabit} navigate={setView} /><button className="focus-note" onClick={() => setView('Eisenhower Matrix')}><Sparkles size={20} /><span><strong>Busy isn’t always productive.</strong><small>Find your focus with the Eisenhower Matrix.</small></span><ArrowUpRight size={18} /></button></div></div></>;
  return <div className={cn('app-shell', collapsed && 'sidebar-is-collapsed')}><a className="skip-link" href="#main">Skip to content</a><Sidebar view={view} setView={setView} collapsed={collapsed} toggle={() => setCollapsed(!collapsed)} search={() => setSearchOpen(true)} add={openAdd} count={today.length - completed} mobileOpen={mobileOpen} closeMobile={() => setMobileOpen(false)} userName={user.name} userEmail={user.email} /><main id="main" className="main-content">{view === 'Inbox' ? <InboxView tasks={tasks} composing={inboxComposing} setComposing={setInboxComposing} add={add} toggle={toggle} updateTitle={updateTitle} remove={removeTask} reorder={reorderTasks} openMenu={() => setMobileOpen(true)} search={() => setSearchOpen(true)} /> : <><Header search={() => setSearchOpen(true)} add={openAdd} menu={() => setMobileOpen(true)} userName={user.name} userEmail={user.email} /><div className="workspace-content">{loading && <p className="workspace-status" role="status">Loading your workspace…</p>}{workspaceError && <p className="workspace-error" role="alert">{workspaceError}</p>}{view === 'Today' ? todayView : secondary}<footer className="page-footer"><span>Made for progress, not perfection.</span><span>One day at a time <span className="footer-flower">✳</span></span></footer></div></>}</main><TaskDialog open={addOpen} onOpenChange={setAddOpen} projects={projects} add={add} /><Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="craft-dialog search-dialog"><DialogHeader><DialogTitle>Find your next thing</DialogTitle><DialogDescription>Search tasks across your workspace.</DialogDescription></DialogHeader><div className="search-input-wrap"><Search size={18} /><Input placeholder="Search tasks…" value={query} onChange={event => setQuery(event.target.value)} aria-label="Search tasks" /></div><div className="search-results">{tasks.filter(task => task.title.toLowerCase().includes(query.toLowerCase())).map(task => <button key={task.id} onClick={() => { setView(task.completed ? 'Today' : 'Inbox'); setSearchOpen(false); }}><span>{task.title}</span><small>{task.project} · {task.completed ? 'Completed' : task.due}</small></button>)}{!tasks.some(task => task.title.toLowerCase().includes(query.toLowerCase())) && <p>No tasks found. Try a different search.</p>}</div></DialogContent></Dialog><span role="status" className="sr-only">{announcement}</span></div>;
}
