'use client';
import { ArrowUpRight, ArrowRight, BookOpen, Footprints, NotebookPen, Flame, Check, CalendarDays, CircleCheck, Target, TrendingUp } from 'lucide-react';
import { initialHabits, weekProgress } from '@/data/mock-data';
import type { Task, View } from '@/types/task';
import { cn } from '@/lib/utils';
export function SummaryCards({ completed, total, habitCount, priorities }: {completed:number;total:number;habitCount:number;priorities:number}) {
 return <div className="summary-grid"><div className="summary-card"><span className="summary-icon lavender"><CircleCheck size={20}/></span><div><span className="eyebrow">Tasks completed</span><div className="summary-value">{completed}<span> / {total}</span></div></div><span className="summary-caption">One step at a time</span></div><div className="summary-card"><span className="summary-icon peach"><Target size={20}/></span><div><span className="eyebrow">Your focus today</span><div className="summary-value">{priorities}<span> priorities</span></div></div><span className="summary-caption">Make time for what matters</span></div><div className="summary-card"><span className="summary-icon sage"><Flame size={20}/></span><div><span className="eyebrow">Habits checked in</span><div className="summary-value">{habitCount}<span> / 3</span></div></div><span className="summary-caption">Small habits, lasting change</span></div></div>;
}
export function Deadlines({tasks,navigate}:{tasks:Task[];navigate:(view:View)=>void}) {
 const upcoming=tasks.filter(t=>t.due!=='today'&&t.due!=='inbox'&&!t.completed);
 return <section className="card deadlines-card"><div className="small-card-heading"><h2>On the horizon</h2><CalendarDays size={17}/></div><p className="card-subtitle">A little heads-up for what’s next.</p>{upcoming.length ? upcoming.slice(0,3).map((task,index)=><div className="deadline" key={task.id}><div className={cn('deadline-date',index===0&&'warm')}><span>{index===0?'NEXT':'SOON'}</span><CalendarDays size={19}/></div><div><strong>{task.title}</strong><span>{task.project} <i>·</i> {task.due}</span></div></div>) : <p className="card-subtitle">You’re all caught up.</p>}<button className="text-link" onClick={()=>navigate('Upcoming')}>View upcoming <ArrowRight size={14}/></button></section>;
}
export function HabitsCard({habits,toggle,navigate}:{habits:typeof initialHabits;toggle:(id:string)=>void;navigate:(view:View)=>void}) {
 const icons={book:BookOpen,move:Footprints,journal:NotebookPen};
 return <section className="card habits-card"><div className="small-card-heading"><h2>Little habits, big things</h2><span className="tiny-pill">DAILY</span></div><p className="card-subtitle">Keep showing up for yourself.</p>{habits.map(habit=>{const Icon=icons[habit.icon as keyof typeof icons];return <div className="habit-row" key={habit.id}><span className={cn('habit-icon',habit.icon)}><Icon size={18}/></span><div className="habit-copy"><strong>{habit.name}</strong><span><Flame size={12}/>{habit.streak} day streak</span></div><button className={cn('habit-check',habit.done&&'done')} onClick={()=>toggle(habit.id)} aria-label={`${habit.done?'Uncheck':'Check in'} ${habit.name}`} aria-pressed={habit.done}>{habit.done&&<Check size={13}/>}</button></div>})}<button className="text-link" onClick={()=>navigate('Habits')}>All your habits <ArrowRight size={14}/></button></section>;
}
export function WeeklyProgress({navigate,completed}:{navigate:(view:View)=>void;completed:number}) {
 const total=19+completed;
 return <section className="card weekly-card"><div className="weekly-copy"><div className="section-kicker"><TrendingUp size={14}/> THE BIGGER PICTURE</div><h2>A good week in the making.</h2><p>You’ve completed <strong>{total} tasks</strong> this week.<br/>Keep building on those little wins.</p><button className="text-link" onClick={()=>navigate('Reports')}>Your weekly report <ArrowUpRight size={14}/></button></div><div className="weekly-chart" aria-label={`Weekly activity: ${total} tasks completed`}><div className="chart-bars">{weekProgress.map((d,i)=><div className="chart-column" key={i}><span className={cn('chart-bar',i===3&&'current',i>3&&'future')} style={{height:`${Math.max(8,(i===3?completed:d.value)*10)}px`}} title={`${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i]}: ${i===3?completed:d.value} tasks`} /><span className={cn(i===3&&'current-day')}>{d.day}</span></div>)}</div><div className="chart-legend"><span/>Tasks completed this week</div></div></section>;
}
