'use client';
import type { Task, View } from '@/types/task';
import { TaskList } from './task-list';
import { HabitsCard, WeeklyProgress } from './overview-cards';
import { initialHabits } from '@/data/mock-data';
export function SecondaryView({view,tasks,toggle,add,habits,toggleHabit,navigate}:{view:View;tasks:Task[];toggle:(id:string)=>void;add:()=>void;habits:typeof initialHabits;toggleHabit:(id:string)=>void;navigate:(v:View)=>void}) {
 if(view==='Inbox'||view==='Upcoming') return <TaskList title={view} tasks={tasks.filter(t=>view==='Inbox'?t.due==='inbox':t.due!=='today'&&t.due!=='inbox')} toggle={toggle} add={add}/>;
 if(view==='Habits') return <HabitsCard habits={habits} toggle={toggleHabit} navigate={navigate}/>;
 if(view==='Reports') return <><WeeklyProgress navigate={navigate} completed={tasks.filter(t=>t.due==='today'&&t.completed).length}/><p className="preview-note">Sample weekly activity · Detailed reports will be part of a future iteration.</p></>;
 if(view==='Eisenhower Matrix') return <div className="matrix-grid">{[{title:'Do first',subtitle:'Urgent & important',priority:'high'},{title:'Schedule',subtitle:'Important, not urgent',priority:'medium'},{title:'Delegate',subtitle:'Urgent, less important',priority:'low'},{title:'Let go',subtitle:'Neither urgent nor important',priority:'none'}].map((q,i)=><section className={`card matrix-cell quadrant-${i}`} key={q.title}><span className="section-kicker">0{i+1}</span><h2>{q.title}</h2><p>{q.subtitle}</p>{tasks.filter(t=>!t.completed&&t.priority===q.priority).map(t=><div className="matrix-task" key={t.id}>{t.title}</div>)}{q.priority==='none'&&<p className="preview-note">More space for what matters.</p>}</section>)}<p className="preview-note">Illustrative priority grouping · Drag-and-drop and urgency controls are planned for later.</p></div>;
 if(view==='Settings')return <section className="card settings-card"><h2>Your personal workspace</h2><div className="settings-profile"><span className="avatar">N</span><div><strong>Neha Mary</strong><p>Craftask · Frontend preview</p></div></div><p>This first mockup uses sample data. Changes last for this session; account settings and cloud sync will come later.</p></section>;
 const days=Array.from({length:view==='Monthly Plan'?28:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d;});
 return <section className="card planner-card"><div className="card-heading"><div><h2>{view==='Calendar'?'Make time for what matters':view}</h2><p>A preview of the days ahead.</p></div></div><div className={view==='Monthly Plan'?'month-grid':'planner-grid'}>{days.map((day,i)=><div className="planner-day" key={day.toISOString()}><span>{day.toLocaleDateString('en',{weekday:'short'})}</span><strong>{day.getDate()}</strong>{tasks.filter(t=>i===0?t.due==='today'&&!t.completed:i===1?t.due==='tomorrow':i===3?t.due==='in 3 days':false).map(t=><p key={t.id}>{t.title}</p>)}</div>)}</div><p className="preview-note">Planning preview · Event editing will be added in a future iteration.</p></section>;
}
