'use client';
import { useState } from 'react';
import { Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { Task } from '@/types/task';
export function TaskDialog({open,onOpenChange,add}:{open:boolean;onOpenChange:(open:boolean)=>void;add:(task:Task)=>void}) {
 const [title,setTitle]=useState('');const [project,setProject]=useState('Personal');const [priority,setPriority]=useState<Task['priority']>('medium');const [due,setDue]=useState('today');
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="craft-dialog"><DialogHeader><DialogTitle>Make space for your next idea.</DialogTitle><DialogDescription>Capture it now. Take it one step at a time.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!title.trim())return;add({id:crypto.randomUUID(),title:title.trim(),project,priority,due,completed:false,matrixQuadrant:null});setTitle('');onOpenChange(false);}}><label className="field-label" htmlFor="task-title">Task name</label><Input id="task-title" placeholder="What would you like to get done?" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={180} autoFocus/><div className="form-grid"><label className="field-label">Project<select value={project} onChange={e=>setProject(e.target.value)}>{['Personal','Craftask','Personal growth','Wellbeing','Academics'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">Priority<select value={priority} onChange={e=>setPriority(e.target.value as Task['priority'])}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div><label className="field-label">When<select value={due} onChange={e=>setDue(e.target.value)}><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="in 3 days">Later this week</option><option value="inbox">No date · Inbox</option></select></label><div className="dialog-actions"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={!title.trim()}><Plus size={16}/>Add task</Button></div></form></DialogContent></Dialog>;
}
